# Generated by Django 5.2.16 on 2026-08-02 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('property_type', models.CharField(choices=[('PG', 'PG'), ('Coliving', 'Coliving'), ('Home', 'Home')], max_length=20)),
                ('stay_type', models.CharField(max_length=20)),
                ('owner_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='phone number must contain 10 digites', regex='^\\d{10}$')])),
                ('property_img', models.ImageField(blank=True, null=True, upload_to='property/')),
            ],
        ),
    ]
