# Generated by Django 5.2.16 on 2026-08-06 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_owner', models.CharField(max_length=20)),
                ('category_type', models.CharField(max_length=10)),
                ('security_deposit', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('location_link', models.URLField()),
                ('rent', models.IntegerField()),
                ('property_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_details', to='living_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='property_interior_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_interior_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='interior/')),
                ('property_interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_interior', to='living_app.property')),
            ],
        ),
    ]
